version: '3.7'

services:
  thr:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=secretkeygoeshere
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/web
    ports:
      - "8080:8080"
    depends_on:
      - thr

volumes:
  static_data: