version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./thr:/thr
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "thr_db"
      MYSQL_USER: "thr_dev"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"