version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/thr
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             # Build elasticsearch index
             #python manage.py search_index --rebuild -f &&
             # Create the super user automatically using environment variables below
             # || true; is added to ignore the error in case the user exists already
             # It works only with Django 3+
             #python manage.py createsuperuser --noinput || true;
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@mail.com
      - DJANGO_SUPERUSER_PASSWORD=password
    depends_on:
      - mysql
      - elasticsearch
    networks:
      - dbnet
      - stacknet

  mysql:
    container_name: mysql
    image: mysql:$MYSQL_VERSION
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "thr_db"
      MYSQL_USER: "thr_dev"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - dbnet

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # https://discuss.elastic.co/t/problems-with-access-to-elasticsearch-form-outside-machine/172450
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - stacknet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - stacknet
    depends_on:
      - elasticsearch

networks:
  stacknet: {}
  dbnet: {}