# Generated by Django 2.2 on 2020-09-24 19:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trackdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('genomics', 'genomics'), ('epigenomics', 'epigenomics'), ('transcriptomics', 'transcriptomics'), ('proteomics', 'proteomics')], default='genomics', max_length=50)),
                ('hub', django_mysql.models.JSONField(default=dict)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(default='v1.0', max_length=10)),
            ],
        ),
    ]
