# Generated by Django 2.2 on 2020-09-14 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackhubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdb',
            name='created',
            field=models.DateField(default=datetime.date.today, max_length=50),
        ),
    ]
